version: 2
updates:
  # Check for updates to GitHub Actions every weekday
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

# Until Dependabot provides Scala updates, they are are handed by the Scala Steward action.
# https://github.com/target/data-validator/blob/master/.github/workflows/scala-steward.yaml
# Check periodically for updates: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
